### ISSUE TITLE
Configure monkey tests?

### ISSUE THREAD

**Issue by miszmaniac** [novoda/gradle-android-command-plugin#100]
I know that's a bad place to ask questions... but I can't find better place:)

Could you explain a little how to:
1. Choose device for monkey tests
2. How to pass additional params to monkey runner, for example swipe frequency?

I found that I could do 
```
command {
    deviceId "deviceName"
}
```
But how to pass those in commandLine

**Comment by xrigau** [comment]
hey @miszmaniac 

For 1. if you want to pass a device id from a command line argument you can do it yourself by using gradle properties

```groovy
command {
  deviceId System.getProperty("device")
}
```

and now you can run the monkey task from the command line and just add the property

```
./gradlew yourMonkeyTask -Pdevice="DEVICE ID"
```

For 2. (additional params) you'll have to create a custom task that overrides the method that executes the monkey task https://github.com/novoda/gradle-android-command-plugin/blob/develop/gradle-android-command-plugin/src/main/groovy/com/novoda/gradle/command/Monkey.groovy#L19-L27

and you want to add the custom arguments there

This is an example of how extend the Money class https://github.com/novoda/spikes/blob/master/monkey-runner/plugin/src/main/groovy/com/novoda/monkey/TargetedMonkey.groovy

and just edit to your preference to override the method mentioned above and add your custom `arguments`

and then you can just create and use your custom task.

From your gradle script (after you have applied the command plugin):

```groovy
def monkey = project.task("runMonkeyWithArguments", type: TargetedMonkey /* Use the right class name */, dependsOn: 'installRelease' /* Use the right install task name */) {
    // packageName = 'you can override it if you need'
    events = 50000
    arguments = ['foo', 'bar']
  }
```

now you can run `./gradlew runMonkeyWithArguments` and the same idea applies here, you could pass them in via command line arguments

hope this helps @miszmaniac

**Comment by miszmaniac** [comment]
Thanks! 
Cool idea for plugin!

**Comment by tasomaniac** [comment]
Also, it is not documented but almost all configuration possible in `command {}` extension can be provided by command line arguments. `deviceId` is already available for example. 

`./gradlew runDebug -DdeviceId=SERIAL_NUMBER`
