### ISSUE TITLE
PR-10: Add file transfer task

### ISSUE THREAD

**Issue by stefanhoth** [novoda/gradle-android-command-plugin#11]
<a href="https://github.com/stefanodacchille"><img src="https://avatars.githubusercontent.com/u/323267?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stefanodacchille](https://github.com/stefanodacchille)**
_Saturday Mar 29, 2014 at 08:35 GMT_
_Originally opened as https://github.com/novoda/legacy-gradle-android-command-plugin/pull/10_

----

I'm not entirely happy with the API atm, I'd have loved to have a configuration closure instead, something like:
```
command {
  ...
  push {
    localFile 'img.jpg'
    remoteFile 'sdcard/Pictures/img.jpg
  }
}
```
but I'm not sure how to implement this. If anyone can give me any inputs on how to achieve it, I'd be happy to put more work on it.

----

_**[stefanodacchille](https://github.com/stefanodacchille)** included the following code: https://github.com/novoda/legacy-gradle-android-command-plugin/pull/10/commits_

**Comment by friedger** [comment]
Could be closed as this is fixed by https://github.com/novoda/gradle-android-command-plugin/commit/19544efdce65ee6e5222fbdc8dafa1dba8c8b909

**Comment by xrigau** [comment]
Fixed in https://github.com/novoda/gradle-android-command-plugin/pull/66
