### ISSUE TITLE
Move to deviceProvider from adb command

### ISSUE THREAD

**Issue by stefanhoth** [novoda/gradle-android-command-plugin#12]
<a href="https://github.com/charroch"><img src="https://avatars.githubusercontent.com/u/29667?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [charroch](https://github.com/charroch)**
_Monday Mar 31, 2014 at 17:32 GMT_
_Originally opened as https://github.com/novoda/legacy-gradle-android-command-plugin/issues/11_

---

DeviceProvider is the standard Android plugin way to get a device which implements IShellExecutable. We could use that to execute the commands rather then adb

https://github.com/novoda/android-tools-base/blob/idea133/build-system/builder-test-api/src/main/java/com/android/builder/testing/api/DeviceConnector.java

**Comment by stefanhoth** [comment]
Here's a sample for DeviceProvider provided by Xavier from the Google Tools team.

https://github.com/manymo/AndroidBuildSystemPlugin/blob/master/src/main/groovy/com/manymo/ManymoDeviceConnector.java

**Comment by tasomaniac** [comment]
This would be really cool because then we would have real specific exceptions on different errors like installation, uninstallation.
