### ISSUE TITLE
Create DSL to configure start task

### ISSUE THREAD

**Issue by hem-brahmbhatt** [novoda/gradle-android-command-plugin#123]
It would be useful to have a task to call the activity manager, so tasks can be written to fire actions on android.

e.g. Launching an action, such as deeplinking to a certain part of your app.
```
adb shell am start  \
-W \
-a android.intent.action.VIEW  \
-d http://www.thetimes.co.uk/edition/news/some-article
```

**Comment by tasomaniac** [comment]
This is definitely a good idea. We started to create DSL's for different `adb shell` applications. 
We are planning to cover them one by one. `am` can definitely be the next since it seems to be quite useful.

**Comment by tasomaniac** [comment]
The 2.0 version of the plugin includes `start` dsl to configure custom start tasks. This issue should extend that to include deeplinking support. 

Suggested dsl 

```groovy
command {
    start {
        someArticle {
            action 'android.intent.action.VIEW'
            data 'http://www.thetimes.co.uk/edition/news/some-article'
            extra key1: 'value1'
            extra key2: 'value2'
        }
    }
}
```
