### ISSUE TITLE
Could not find com.novoda:gradle-android-command-plugin:1.4.0

### ISSUE THREAD

**Issue by h0lmiew** [novoda/gradle-android-command-plugin#150]
I'm seeing this error when I build my project on a Mac, using gradle. 

**The project builds fine on PC**.
 
The correct Android SDK, and also JDK is installed on the Mac.
The build gradle correctly references jcenter() as required in repositories.
The dependency for class path is also defined in dependencies.
The plugin is applied in the build gradle.
I tried also adding the repository for snapshots.

On Mac (Two different ones even), I get this error:

`
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ProjectName'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.novoda:gradle-android-command-plugin:2.1.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.pom
       - https://jcenter.bintray.com/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.jar
       - https://repo.maven.apache.org/maven2/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.pom
       - https://repo.maven.apache.org/maven2/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.jar
       - https://plugins.gradle.org/m2/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.pom
       - https://plugins.gradle.org/m2/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.jar
       - https://dl.bintray.com/novoda-oss/snapshots/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.pom
       - https://dl.bintray.com/novoda-oss/snapshots/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.jar
       - https://dl.google.com/dl/android/maven2/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/novoda/gradle-android-command-plugin/2.1.0/gradle-android-command-plugin-2.1.0.jar
     Required by:
         project :
`

What am I missing? Thanks

**Comment by mr-archano** [comment]
Hi @h0lmiew unfortunately we are experiencing some issues with our Bintray account, where some packages are not showing up in JCenter even if correctly released and marked as in sync with JCenter.
We have contacted the Bintray support and they're working on it, but the workaround for now is to add the maven repo from the Bintray account to your buildscript repos:
```
buildscript {
    repositories {
         maven {
            url = 'https://dl.bintray.com/novoda-oss/maven/'
         }
    }
}
```

**Comment by h0lmiew** [comment]
Thank you for the update @mr-archano , I will try again on Monday

**Comment by Deracination** [comment]
The maven workaround fixed it for me. Thank you

**Comment by h0lmiew** [comment]
I can successfully build now without using the workaround, will close it. Thank you

**Comment by mr-archano** [comment]
@h0lmiew it's working indeed. I found this morning an email from the support team mentioning that the issue with JCenter syncing is resolved ✨
