### ISSUE TITLE
Add grant permission command

### ISSUE THREAD

**Issue by stefanhoth** [novoda/gradle-android-command-plugin#17]
<a href="https://github.com/grujo"><img src="https://avatars.githubusercontent.com/u/923176?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grujo](https://github.com/grujo)**
_Friday Apr 25, 2014 at 10:18 GMT_
_Originally opened as https://github.com/novoda/legacy-gradle-android-command-plugin/issues/16_

---

Something like https://gist.github.com/xrigau/11284124

**Comment by devisnik** [comment]
There are some comments on the gist above. Is this still valid with the new manifest merger? 
/cc @xrigau

**Comment by xrigau** [comment]
I haven't updated it in a while, there might be better solutions to be fair. This looks like something we could look at :+1:
