### ISSUE TITLE
Tasks description should make it clear that they came from this GACP plugin

### ISSUE THREAD

**Issue by paulvi** [novoda/gradle-android-command-plugin#37]
Especially for a beginner it is not clear which tasks came from where, and how to configure them.

Tasks description should include GACP or some other note to distinguish

**Comment by tasomaniac** [comment]
There is an ongoing task to create more documentation around what plugin does. I hope that will be useful to make things clear. Closing this issue for now.

**Comment by paulvi** [comment]
Tasks descriptor appear after command

`gradle tasks`,

Documentation is related, but alone will not appear on command line response

**Comment by tasomaniac** [comment]
Thanks for quick reply. I hope that the descriptions are clearly describing what tasks are doing. If that is so, the place that the tasks are coming from is not as much important. 

I hope the documentation will be clear about the tasks automatically added.

**Comment by paulvi** [comment]
It was not about documentation, but about `gradle tasks` output.

It should be like

```
$ gradle tasks
task1 descr 
task2 GACP: descr2
task3 GACP: descr3
task4 descr4
```

So when new user looks at that output, he/she immediately can tell, that task2 and task3 came from GACP plugin, and so he/she needs to look into GACP documentation.

The problem with gradle once, there are many plugins in the build, it is not that transparent what each plugin has contributed, and what docs to check.

Having some prefix in `gradle tasks` output can help that.

Possibly this issue should be raised against gradle itself.  
But when I was looking at this plugin, I found it hard to remember what exactly new extensions were.
