### ISSUE TITLE
It'd be nice if the deviceId could be cached

### ISSUE THREAD

**Issue by xrigau** [novoda/gradle-android-command-plugin#47]
This would make sure both installation of the app and the monkey run on the same device

**Comment by devisnik** [comment]
:+1: 
There are some inconsistencies in when the `deviceId` is computed, depending on how it is defined it might be at evaluation or at task execution (if given as a closure).

**Comment by tasomaniac** [comment]
Although this can be done by caching the value. It can also be achieved manually by providing a `deviceId` closure. The closure itself can cache the value. 
Or alternatively the deviceId can be provided with a command line argument which will make it fixed. 

Maybe we need more examples. What do you think?

Otherwise, whatever default behavior

**Comment by xrigau** [comment]
yeah, when I created the issue we had the following use case:
 - the monkey task runs every night on the CI as part of the nightly task
 - the CI has many devices connected to it (more than 5)
 - we want the monkey to run on various devices but we don't want the nightly job to run for too long because there's other jobs as well so we get the list of connected devices and pick a random one (this is done using `devices` and `deviceId` which are part of the plugin)
 - since it uses a random and `deviceId` is re-evaluated every time, the `install` task will evaluate to device A and then the `monkey` task will evaluate to device B but you'd expect both things to happen on the same device

**Comment by tasomaniac** [comment]
@xrigau I think it is easier to do that locally by having a deviceId closure that takes care of the need. 

I think it is hard to have some cache that is valid for everyone. How would you invalidate the cache then?

Did you guys find a solution to the monkey problem at the end?

**Comment by devisnik** [comment]
@xrigau The problem you describe might be solved via the `@Memoized` we introduced here: https://github.com/novoda/gradle-android-command-plugin/blob/develop/plugin/src/main/groovy/com/novoda/gradle/command/AndroidCommandPluginExtension.groovy#L67

We need to verify that. Do you have any snippets we might use?

**Comment by xrigau** [comment]
This was a long time ago, the code seems to have changed a lot since then in both the project and the plugin so let's close this for now as it seems to be obsolete :)
