### ISSUE TITLE
Possibility to run on all attached devices

### ISSUE THREAD

**Issue by tprochazka** [novoda/gradle-android-command-plugin#58]
I think that default behavior should run app on all attached device, not just first, why?
installDebug will also install app on all attached device

**Comment by emanuelez** [comment]
That would be nice. Especially if such runs could happen in parallel.

**Comment by ataulm** [comment]
I've added this bash script to one of my projects, adbAll.sh

```bash
#!/bin/bash
adb devices | while read line
do
    if [ ! "$line" = "" ] && [ `echo $line | awk '{print $2}'` = "device" ]
    then
        device=`echo $line | awk '{print $1}'`
        echo "$device $@ ..."
        adb -s $device $@
    fi
done
```

which allows me to run `./adbAll.sh uninstall com.ataulm.test` to uninstall the specified package from all connected devices. Not sure where the best place to integrate something like this in the command plugin though, or if another approach would work better.

**Comment by tasomaniac** [comment]
So, I just realized that Android team changed their mind and almost all tasks created by `android` plugin installs on all devices by default. 
Namely all `install`, `uninstall` tasks for variants, `uninstallAll` and `connectedCheck` tasks etc. 

Also they support environment variable `ANDROID_SERIAL` to install on a specific devices. The env variable can be comma separated serial numbers of devices. It runs the task on provided devices.

This should be something we should look into. 

Here some related AOSP issues: 
- Support in `uninstall` tasks: https://code.google.com/p/android/issues/detail?id=59894
- support for `connectedCheck` task: https://code.google.com/p/android/issues/detail?id=75407
- support for multiple devices: https://code.google.com/p/android/issues/detail?id=180700

Also here is a hack that supports `-Pdevices` gradle command line args.
Runs like this: `./gradlew connectedAndroidTest -Pdevices=<serial_number1>,<serial_number2>`
https://gist.github.com/Ghedeon/79db271a91283f5a7109

**Comment by tasomaniac** [comment]
After talking with @devisnik we decided that it would be logical thing to run tasks on all connected devices by default. 

We need to do this in such a way that it would be extensible and easy to support parallel runs in the future. 

We also plan to support various ways to specify deviceIds so that it runs on a subset of devices. Those either can be supported by the plugin or can be samples that achieve various things by utilizing what is already there.
