### ISSUE TITLE
Monkey running only on devices with the sdkVersion

### ISSUE THREAD

**Issue by danybony** [novoda/gradle-android-command-plugin#62]
Add by default some filter on the device.sdkVersion, some similar to
```
def minSdkDevices = devices().grep({
                it.sdkVersion() >= defaultConfig.minSdkVersion.getApiLevel()
})
```

**Comment by devisnik** [comment]
:+1:

**Comment by blundell** [comment]
This is now possible: https://github.com/novoda/gradle-android-command-plugin/blob/develop/sample/build.gradle#L67
