### ISSUE TITLE
Provide monkey start parameters

### ISSUE THREAD

**Issue by ouchadam** [novoda/gradle-android-command-plugin#71]
Expose in the api the ability to provide the monkey package/action/activity start parameters 

>adb shell am start in order to start the desired subactivity

`adb shell am start -a my.package.app.ACTION1 -n my.package.app/.sub.MyActivity`

**Comment by devisnik** [comment]
Looking at http://developer.android.com/tools/help/monkey.html it seems that a direct specification of the activity to be launched is not supported via monkey.

We might add support for the `-c` option though, such that you could specify category `Intent.CATEGORY_MONKEY` and explicitly set that in your manifest. 

Other ideas?

**Comment by blundell** [comment]
Fixed by https://github.com/novoda/gradle-android-command-plugin/pull/90
