### ISSUE TITLE
apkPath source defined in VariantConfigurator

### ISSUE THREAD

**Issue by tprochazka** [novoda/gradle-android-command-plugin#74]
I don't know why it is really bug.
But in the ```VariantConfigurator.groovy``` you are using ```variant.outputs[0].packageApplication.outputFile``` as source for the final APK which will be deployed to the phone.

But if I use this to the remote sign:
https://gist.github.com/ducrohet/e0d854c54bd0ceeb7044
```output[0].packageApplication.outputFile``` contain only usigned apk.

But real target name is ```output[0].outputFile```

So why you are using ```packageApplication.outputFile``` instead?

**Comment by tprochazka** [comment]
It's definitely bug, because also with default sign way it try to upload unaligned version to the device.

**Comment by devisnik** [comment]
Thanks for reporting, We'll have to double check. PR welcome. ;)

**Comment by tprochazka** [comment]
I have no problem to do PR, but it is only change one line of code, administration with the pull request take more time than change itself.

**Comment by tprochazka** [comment]
Great. It works! Thanks!
