### ISSUE TITLE
Collect mokeyrunner log

### ISSUE THREAD

**Issue by emartynov** [novoda/gradle-android-command-plugin#75]
Thank you for the plugin!

I have a question which I was not able to grab from sources or documentation. Is log from monkeyrunner collected somewhere?

**Comment by devisnik** [comment]
The monkey task just pipes the output into the logger, so you run Gradle with the `--info` option to see it in the output. Do you need more than that?

**Comment by emartynov** [comment]
Thanks for answer! It would be helpful to have monkey runner log for investigation. I think would be nice task for contribution.

Sure I can split tasks in jenkins run and set only for monkey runner --info level.

**Comment by blundell** [comment]
you can pipe the output into a file.

We can look at adding this as a feature, closing this as not an issue for now.
