### ISSUE TITLE
Use property `adbExe` of Android plugin

### ISSUE THREAD

**Issue by friedger** [novoda/gradle-android-command-plugin#91]
There is a property to access adb executable: http://stackoverflow.com/a/34538979/243599

**Comment by blundell** [comment]
can you explain more why and where we should change this? (otherwise we'll just have to close the issue because we don't understand).

**Comment by stefanhoth** [comment]
@blundell I guess @friedger suggests to not rely on adb being in the path if there's another way to get the executable. 

Right now we rely on the path https://github.com/novoda/gradle-android-command-plugin/blob/develop/gradle-android-command-plugin/src/main/groovy/com/novoda/gradle/command/AdbCommand.groovy

**Comment by friedger** [comment]
@stefanhoth guessed right. The plugin tries to figure out where adb is located (https://github.com/novoda/gradle-android-command-plugin/blob/develop/gradle-android-command-plugin/src/main/groovy/com/novoda/gradle/command/AndroidCommandPluginExtension.groovy#L54) but could rely on the Android plugin to do it correctly.

An even more precise description:
http://stackoverflow.com/a/26771087/243599

**Comment by ouchadam** [comment]
:100:  we should definitely do this, I raised a bug on another project for relying on `adb` to be on the `PATH`

**Comment by tasomaniac** [comment]
The plugin does not rely on `adb` being on the path`. 
It asks `android` gradle plugin to give Android home folder path. Then it assumes that it is under `"$androidHome/platform-tools/adb"`

Every Android project needs Android SDK installation and it will have `adb` in that path. 

But the value in the extension is configurable. If you want to use some other `adb` in an other place, 
This worked for me:

```groovy
android {
    ...

    command {
        adb '/Users/tasomaniac/android-sdk/platform-tools/adb'
    }
}
```
