### ISSUE TITLE
Add to plugins.gradle.org

### ISSUE THREAD

**Issue by jaredsburrows** [novoda/gradle-android-command-plugin#95]
Please add this to https://plugins.gradle.org.

**Comment by tasomaniac** [comment]
We already have this user there: https://plugins.gradle.org/plugin/com.novoda.sqlite-analyzer
And the plugin there is already outdated. 

We publish our plugins to bintray automatically, using [bintray-release](https://github.com/novoda/bintray-release). So it will just add more complication into release process if we also start publishing there. 

We will close this issue for now. Thanks for the suggestion.

**Comment by jaredsburrows** [comment]
@tasomaniac Can we reopen this and publish to https://plugins.gradle.org ?

**Comment by tasomaniac** [comment]
It would be nice but I don't have access to Novoda repos and CI anymore. I am not sure if anybody from Novoda would take it and publish it.
