### ISSUE TITLE
Add "installAll" task

### ISSUE THREAD

**Issue by jaredsburrows** [novoda/gradle-android-command-plugin#99]
https://github.com/JakeWharton/u2020/blob/master/build.gradle#L193

**Comment by frapontillo** [comment]
Is it worth considering to add a `all` variant for all tasks?

**Comment by jaredsburrows** [comment]
Yeah, there is already an "uninstallAll". Can we add an "installAll"? Just thought it would be an easy add.

**Comment by tasomaniac** [comment]
@frapontillo although it makes sense to add `all` variant to to most of the tasks, it cannot be added to all. Some of them are not variant specific. `monkey` and `enable/disableSystemAnimations` namely. 

Months ago, I tried to split tasks depending on specific variant and accessing the APK file for that variant vs general device related tasks. I was not super happy about it. I will try once more.
